version: '2'
services:
  db:
    image: postgres
    container_name: database
  api:
    build: ./api
    volumes:
      - ./api:/api
    depends_on:
      - db
    container_name: api
  app:
    build: ./rocker-app
    command: npm start
    volumes:
      - ./rocker-app:/rocker-app
      - /rocker-app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
    container_name: app